# -*- coding: utf-8 -*-
"""Medical ChatBot AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x4urLM9JYckJQZVJ3cUcjLSmoDPGWinZ
"""

# Install dependencies
!pip install langchain langchain-community faiss-cpu pypdf sentence-transformers transformers accelerate gradio

# Imports
import os
from langchain_community.document_loaders import PyPDFLoader
from langchain.text_splitter import CharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings
from transformers import pipeline
from langchain.llms import HuggingFacePipeline
from langchain.chains import RetrievalQA
import gradio as gr

from google.colab import files
uploaded = files.upload()
pdf_path = list(uploaded.keys())[0]

# Load PDF
loader = PyPDFLoader(pdf_path)
documents = loader.load()

# Split text into chunks (smaller to avoid >512 token input)
text_splitter = CharacterTextSplitter(chunk_size=200, chunk_overlap=50)
docs = text_splitter.split_documents(documents)

# Embeddings
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

# Vector DB
db = FAISS.from_documents(docs, embeddings)
retriever = db.as_retriever()

# Load Hugging Face model locally (no API calls)
generator = pipeline(
    "text2text-generation",
    model="google/flan-t5-large",
    max_length=512,
    device=0  # CPU (set 0 if GPU is available)
)

# Wrap pipeline into LangChain
llm = HuggingFacePipeline(pipeline=generator)

qa = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=retriever,
    return_source_documents=False   # ✅ only one output now
)

def ask_bot(query):
    try:
        result = qa.run(query)  # works fine now
        return result + "\n\n⚠️ Disclaimer: This is AI from Gale Encyclopedia, not medical advice."
    except Exception as e:
        return f"⚠️ Error: {str(e)}"

pip install streamlit

st.title("🚀 Medical ChatBot AI")
user_input = st.text_input("Enter your medical question:")
if st.button("Get Answer"):
    answer = ask_bot(user_input)
    st.write(answer)

